USE [master]
GO

/****** Object:  Database [netprojekt]    Script Date: 22.04.2021 10:19:26 ******/
CREATE DATABASE [netprojekt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'netprojekt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\netprojekt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'netprojekt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\netprojekt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [netprojekt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [netprojekt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [netprojekt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [netprojekt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [netprojekt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [netprojekt] SET ARITHABORT OFF 
GO

ALTER DATABASE [netprojekt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [netprojekt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [netprojekt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [netprojekt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [netprojekt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [netprojekt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [netprojekt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [netprojekt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [netprojekt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [netprojekt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [netprojekt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [netprojekt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [netprojekt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [netprojekt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [netprojekt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [netprojekt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [netprojekt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [netprojekt] SET RECOVERY FULL 
GO

ALTER DATABASE [netprojekt] SET  MULTI_USER 
GO

ALTER DATABASE [netprojekt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [netprojekt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [netprojekt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [netprojekt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [netprojekt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [netprojekt] SET QUERY_STORE = OFF
GO

ALTER DATABASE [netprojekt] SET  READ_WRITE 
GO


